### ISSUE TITLE
Moving into Next.js examples repo?

### ISSUE THREAD

**Issue by leerob** [SuttonJack/vanilla-extract-app-dir#2]
Would you be open to moving this into the Next.js examples repo as a PR? (And updating the deps, removing the experimental flag)?

**Comment by SuttonJack** [comment]
@leerob  https://github.com/vercel/next.js/pull/50394

Note that the experimental flag is required at the moment for the VE plugin - see:
1. https://github.com/vanilla-extract-css/vanilla-extract/issues/1087
2. https://github.com/vercel/next.js/discussions/49892#discussioncomment-5935169

Ideally we can work this out in the near future
